### PR TITLE
bug fix composer command call

### PR DESCRIPTION
**Pull request by nyamsprod**
the command should be `composer require` instead of `composer install`

### CODE REVIEW

**Review by michalbundyra — APPROVED** [review]
👍

**Comment by nyamsprod** [comment]
not sure why the Travis is failing since I've only change some texts 😢

**Comment by michalbundyra** [comment]
@nyamsprod 
> not sure why the Travis is failing since I've only change some texts 

No worries about that, it's fixed in #28

**Comment by weierophinney** [comment]
Thanks, @nyamsprod; merged to develop to release with 2.6.0.

**Pull request closed without merging**
